# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  # Triggers on pull requests to develop branch
  pull_request:
    branches: ["develop"]

  # Triggers on pushes to develop branch and pull request branches
  push:
    branches:
      - "develop"
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"
      - "main"

  # Allows manual triggering
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Clean and Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit
          npm rebuild

      - name: Install Optional Dependencies
        run: |
          npm install @rollup/rollup-linux-x64-gnu --save-dev

      - name: Unit Tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    # Only deploy if it's a PR to develop from the same repo, or if it's a push to main
    if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) || github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true
          wait_deploy: true
          github_deployment: true
          deployment_environment: "production"
          github_token: ${{ secrets.GITHUB_TOKEN }}
